config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'wears/index'
      post 'wears/create'
      delete 'wears/:id', to: 'wears#destroy'
    end
  end
  root 'wears#index'
  #resources :wears
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/wear.rb
class Wear < ApplicationRecord
end

app/controllers/api/v1/wears_controller.rb
class Api::V1::WearsController < ApplicationController
    before_action :set_wear, only: [:show, :edit, :update, :destroy]
  
    # GET /wears
    # GET /wears.json
    def index
      @wears = Wear.all.order(brand: :asc)
      render json: @wears
    end
  
    # GET /wears/1
    # GET /wears/1.json
    def show
      if @wear
        render json: @wear
      else
        render json: @wear.errors
      end
    end
  
    # GET /wears/new
    def new
      @wear = Wear.new
    end
  
    # GET /wears/1/edit
    def edit
    end
  
    # POST /wears
    # POST /wears.json
    def create
      @wear = Wear.new(Wear_params)
  
  
      if @wear.save
        render json: @wear
      else
        render json: @wear.errors
      end
    end
  
    # PATCH/PUT /wears/1
    # PATCH/PUT /wears/1.json
    def update
    end
  
    # DELETE /wears/1
    # DELETE /wears/1.json
    def destroy
      @wear.destroy
  
      render json: { notice: 'Wear was successfully removed.' }
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_Wear
        @wear = Wear.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def Wear_params
        params.permit(:brand, :element, :country, :quantity)
      end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/wears_controller.rb
class WearsController < ApplicationController
  def index
  end
end

app/helpers/api/v1/wears_helper.rb
module Api::V1::WearsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wears_helper.rb
module WearsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsReact</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'index' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/wears/_form.html.erb
<%= form_with(model: wear) do |form| %>
  <% if wear.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wear.errors.count, "error") %> prohibited this wear from being saved:</h2>

      <ul>
        <% wear.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :element %>
    <%= form.text_field :element %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wears/edit.html.erb
<h1>Editing Wear</h1>

<%= render 'form', wear: @wear %>

<%= link_to 'Show', @wear %> |
<%= link_to 'Back', wears_path %>

app/views/wears/new.html.erb
<h1>New Wear</h1>

<%= render 'form', wear: @wear %>

<%= link_to 'Back', wears_path %>

app/views/wears/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @wear.brand %>
</p>

<p>
  <strong>Element:</strong>
  <%= @wear.element %>
</p>

<p>
  <strong>Country:</strong>
  <%= @wear.country %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @wear.quantity %>
</p>

<%= link_to 'Edit', edit_wear_path(@wear) %> |
<%= link_to 'Back', wears_path %>